### ISSUE TITLE
Setup Goerli Node Guide's Docker Compose File Error

### ISSUE THREAD

**Issue by bap2pecs** [0xPolygon/wiki#111]
following docs/zkevm/setup-goerlinode.md, I got error

```
$ docker-compose up -d
ERROR: yaml.scanner.ScannerError: while scanning a simple key
  in "./docker-compose.yml", line 23, column 5
could not find expected ':'
```

this is due to the indentation is off. after fixing the indentation and rerun the command, it still failed:

```
$ docker-compose up -d
ERROR: Invalid interpolation format for "ports" option in service "geth": "0.0.0.0:${L1_RPC_PORT}:8545/$."
```

**Comment by EmpieichO** [comment]
Seeking help from the zkEVM Devs team. Will revert.

**Comment by EmpieichO** [comment]
No response from the Node Devs team. So I searched the internet and got this:

Check this stackOverflow thread, maybe the _docker-compose version_ is the problem https://github.com/Mailu/Mailu/issues/853  

You can also check _variable (and escaping variable) parameters_ in docker-compose.yml https://stackoverflow.com/questions/57241980/invalid-interpolation-format-for-environment-option-in-service-web-secret 

Otherwise check _Docker docs_ here https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by EmpieichO** [comment]
Devs' response: The issue related to the goerli node is a typo, it shouldn't end the variables with '/$'

**Comment by EmpieichO** [comment]
Given previous corrections in merged [PR](https://github.com/0xPolygon/wiki/pull/128) and the new [PR](https://github.com/0xPolygon/wiki/pull/141) ... this issue can be closed.
